### ISSUE TITLE
Problem with CHARMM improper parameters

### ISSUE THREAD

**Issue by jnoske** [Acellera/ffevaluation#3]
Hello,

I think there is a problem with the improper parameters which are defined in the parameter file using wildcards:

O    X    X    C     120.0000         0      0.0000 ! ALLOW   PEP POL ARO

That can not be understood by the following function:
```

def getImproperParameter(type, parameters):
    from itertools import permutations
    type = np.array(type)
    perms = np.array([x for x in list(permutations((0, 1, 2, 3))) if x[2] == 2])
    for p in perms:
        if tuple(type[p]) in parameters.improper_types:
            return parameters.improper_types[tuple(type[p])], "improper_types"
        elif tuple(type[p]) in parameters.improper_periodic_types:
            return (
                parameters.improper_periodic_types[tuple(type[p])],
                "improper_periodic_types",
            )
    raise RuntimeError("Could not find improper parameters for key {}".format(type))
```

Apparently, this problem can also occur for dihedral paramters.

**Comment by stefdoerr** [comment]
Yes I don't believe I ever implemented wildcard parameters. Feel free to add support for them if you want in ffevaluate.

**Comment by jnoske** [comment]
I added some functionalities in the ffevaluate module to account for wildcards in dihedral and improper parameters, how can I provide them?

**Comment by stefdoerr** [comment]
Create a pull request to this repo. Or send me the files in a zip and I will add the changes myself

**Comment by stefdoerr** [comment]
Fixed by https://github.com/Acellera/ffevaluation/pull/4
Thanks a lot for your contribution!
